[package]
 name = "fastboot"
 version = "1.3.1"
 edition = "2021"
 authors = ["TigerHixTang"]
 repository = "https://github.com/TigerHixTang/fh6_fastboot"
 homepage = "https://www.nexusmods.com/forzahorizon6/mods/522"
 description = "Skip Forza Horizon 6 startup videos and black-screen wait."
 
 [lib]
 name = "version"
 crate-type = ["cdylib"]
 
 [dependencies]
 retour = "0.3"
 
 [profile.release]
 opt-level = "z"
 lto = true
 panic = "abort"
 strip = true
 codegen-units = 1
 
